---
cluster_engine: LSF

use_cluster: true

ref: b37

aligner: bwamem
bam_chr1_base_recal: true
bam_dup_type: markdup
bam_no_filter: false
bam_no_recal: false
bam_no_realn: false
bam_no_sort: false
bam_fix_rg: false
bam_phred64: false
bam_reprocess: false

targets_file: ~/share/reference/target_panels/

qsub_priority: 0
...
