ARRIBA_EXE ?= $(HOME)/share/usr/env/arriba-2.0.0/src/arriba_v2.0.0/arriba
ANNOTATION_GTF ?= $(HOME)/share/usr/env/arriba-2.0.0/src/arriba_v2.0.0/GENCODE19.gtf
ASSEMBLY_FA ?= $(HOME)/share/usr/env/arriba-2.0.0/src/arriba_v2.0.0/GRCh37viral.fa
BLACKLIST_TSV ?= $(HOME)/share/usr/env/arriba-2.0.0/src/arriba_v2.0.0/database/blacklist_hg19_hs37d5_GRCh37_v2.0.0.tsv.gz
KNOWN_FUSIONS_TSV ?= $(HOME)/share/usr/env/arriba-2.0.0/src/arriba_v2.0.0/database/known_fusions_hg19_hs37d5_GRCh37_v2.0.0.tsv.gz
PROTEIN_DOMAINS_GFF3 ?= $(HOME)/share/usr/env/arriba-2.0.0/src/arriba_v2.0.0/database/protein_domains_hg19_hs37d5_GRCh37_v2.0.0.gff3
STAR_INDEX_DIR ?= $(HOME)/share/usr/env/arriba-2.0.0/src/arriba_v2.0.0/STAR_index_GRCh37viral_GENCODE19
STAR_THREADS ?= 16